settings {
  properties {
    ai {
      jeffrey.local.ai {
        provider = "none"
        model = "claude-opus-4-6"
        max-tokens = "128000"
      }
    }
    logging {
      logging.level.pbouda.jeffrey = "INFO"
    }
  }

  secrets {
    ai {
      jeffrey.local.ai {
        api-key = ""
      }
    }
  }
}
