settings {
  properties {
    ai {
      jeffrey.local.ai {
        provider = "none"
        model = "claude-opus-4-6"
        max-tokens = "128000"
      }
    }
    logging {
      logging.level.pbouda.jeffrey = "INFO"
    }
    visualization {
      jeffrey.local.visualization.flamegraph {
        min-frame-threshold-pct = "0.05"
        frame-text-mode = "single-line"
      }
    }
  }

  secrets {
    ai {
      jeffrey.local.ai {
        api-key = ""
      }
    }
  }
}
