<!--
  - Jeffrey
  - Copyright (C) 2026 Petr Bouda
  -
  - This program is free software: you can redistribute it and/or modify
  - it under the terms of the GNU Affero General Public License as published by
  - the Free Software Foundation, either version 3 of the License, or
  - (at your option) any later version.
  -
  - This program is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  - GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License
  - along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script setup lang="ts">
import { onMounted } from 'vue';
import DocsCallout from '@/components/docs/DocsCallout.vue';
import DocsCodeBlock from '@/components/docs/DocsCodeBlock.vue';
import DocsNavFooter from '@/components/docs/DocsNavFooter.vue';
import DocsPageHeader from '@/components/docs/DocsPageHeader.vue';
import { useDocHeadings } from '@/composables/useDocHeadings';

const { setHeadings } = useDocHeadings();

const headings = [
  { id: 'init-flow', text: 'Init Flow at Container Start', level: 2 },
  { id: 'env-vars', text: 'Required Environment Variables', level: 2 },
  { id: 'base-conf', text: 'Anatomy of jeffrey-base.conf', level: 2 },
  { id: 'project-block', text: 'Project Block', level: 2 },
  { id: 'capture-blocks', text: 'Capture Blocks', level: 2 },
  { id: 'jvm-options', text: 'Additional JVM Options', level: 2 },
  { id: 'omitted-paths', text: "Why Paths Are Omitted", level: 2 }
];

onMounted(() => {
  setHeadings(headings);
});

const envBlock = `# helm/jeffrey-testapp-server/templates/deployment.yaml
env:
  - name: SPRING_CONFIG_ADDITIONAL_LOCATION
    value: /app/config/application.properties
  - name: JEFFREY_HOME
    value: {{ .Values.sharedVolume.mountPath | quote }}     # /mnt/jeffrey
  - name: JEFFREY_BASE_CONFIG
    value: {{ .Values.jeffrey.baseConfigPath | quote }}     # /jeffrey/jeffrey-base.conf
  - name: JEFFREY_ENABLED
    value: {{ .Values.jeffrey.enabled | quote }}            # "true"
  - name: JEFFREY_TESTAPP_MODE
    value: {{ .Values.mode | quote }}                       # "direct" or "dom"`;

const baseConf = `# helm/jeffrey-testapp-server/jeffrey-base.conf
# Read by \`jeffrey-cli init\` at container start (invoked by the jeffrey-jib entrypoint
# wrapper). Generated by Jeffrey Server's copy-libs feature populates the shared volume
# at \${jeffrey-home}/libs/current/.

# jeffrey-home, profiler-path, agent-path are intentionally omitted:
# jeffrey-cli reads jeffrey-home from the JEFFREY_HOME env var (set by the
# Deployment from sharedVolume.mountPath), and auto-derives profiler-path /
# agent-path as \${jeffrey-home}/libs/current/{libasyncProfiler.so,jeffrey-agent.jar}.

project {
    name  = \${JEFFREY_TESTAPP_MODE}"-jeffrey-testapp-server"
    label = "Jeffrey TestApp Server ("\${JEFFREY_TESTAPP_MODE}")"
}

perf-counters {
    enabled = true
}

heap-dump {
    enabled = true
    type = "crash"
}

jvm-logging {
    enabled = true
    command = "jfr*=trace:file=<<JEFFREY_CURRENT_SESSION>>/jfr-jvm.log::filecount=3,filesize=5m"
}

additional-jvm-options = "-Xmx400m -Xms400m -XX:+UseG1GC -XX:+AlwaysPreTouch"`;

const projectBlock = `project {
    name  = \${JEFFREY_TESTAPP_MODE}"-jeffrey-testapp-server"
    label = "Jeffrey TestApp Server ("\${JEFFREY_TESTAPP_MODE}")"
}`;

const configMapMount = `# In the testapp-server Deployment template
volumeMounts:
  - name: jeffrey-base-config
    mountPath: {{ .Values.jeffrey.baseConfigPath | dir }}    # /jeffrey
    readOnly: true

volumes:
  - name: jeffrey-base-config
    configMap:
      name: {{ include "jeffrey-testapp-server.fullname" . }}-jeffrey-base
      items:
        - key: jeffrey-base.conf
          path: {{ .Values.jeffrey.baseConfigPath | base }}  # jeffrey-base.conf`;
</script>

<template>
  <article class="docs-article">
    <DocsPageHeader
      title="Jeffrey CLI"
      icon="bi bi-terminal"
    />

    <div class="docs-content">
      <p>
        At container start, the
        <router-link to="/docs/server/deployment/jeffrey-jib">JIB-wrapped entrypoint</router-link>
        runs <code>jeffrey-cli init</code> against the per-pod
        <code>jeffrey-base.conf</code>. The CLI resolves paths against the
        <router-link to="/docs/server/deployment/shared-volume">shared volume</router-link>,
        builds the JVM-arg response file, and hands control to <code>java</code>. This
        page documents the contract: which environment variables the CLI expects, which
        ConfigMap-mounted file it reads, and what each block of that file does.
      </p>

      <h2 id="init-flow">Init Flow at Container Start</h2>
      <ol>
        <li>The wrapped entrypoint checks <code>JEFFREY_ENABLED</code>. If it's not <code>true</code>, it skips profiling entirely and <code>exec</code>s the original <code>java</code> command.</li>
        <li>It reads <code>JEFFREY_BASE_CONFIG</code> (the path to the HOCON config inside the container).</li>
        <li>It locates the per-arch CLI binary at <code>${JEFFREY_HOME}/libs/current/jeffrey-cli-&lt;arch&gt;</code> (where <code>&lt;arch&gt;</code> is resolved from <code>uname -m</code>).</li>
        <li>It calls <code>jeffrey-cli init</code>, which reads the HOCON config, derives the agent / profiler paths from <code>JEFFREY_HOME</code>, and emits a JVM-arg response file.</li>
        <li>It launches the JVM with <code>java @&lt;response-file&gt; @/app/jib-classpath-file &lt;MainClass&gt;</code>. The response file injects the <code>-javaagent</code>, the <code>-agentpath</code> for async-profiler, the <code>additional-jvm-options</code>, and the per-feature flags (heap-dump, jvm-logging, perf-counters).</li>
      </ol>

      <h2 id="env-vars">Required Environment Variables</h2>
      <p>Three variables wire the CLI into the pod. Every monitored Deployment in the testapp sets them identically:</p>

      <table>
        <thead>
          <tr>
            <th>Variable</th>
            <th>Default in chart</th>
            <th>Purpose</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><code>JEFFREY_ENABLED</code></td>
            <td><code>"true"</code></td>
            <td>Master toggle. Setting it to <code>"false"</code> bypasses profiling entirely without rebuilding the image.</td>
          </tr>
          <tr>
            <td><code>JEFFREY_HOME</code></td>
            <td><code>/mnt/jeffrey</code> (= <code>sharedVolume.mountPath</code>)</td>
            <td>Root of the shared volume. The CLI binary, agent JAR, and async-profiler library are resolved relative to <code>${JEFFREY_HOME}/libs/current/</code>.</td>
          </tr>
          <tr>
            <td><code>JEFFREY_BASE_CONFIG</code></td>
            <td><code>/jeffrey/jeffrey-base.conf</code></td>
            <td>Path inside the container to the HOCON config (mounted via ConfigMap).</td>
          </tr>
        </tbody>
      </table>

      <p>From
        <a href="https://github.com/petrbouda/jeffrey-testapp/blob/main/helm/jeffrey-testapp-server/templates/deployment.yaml" target="_blank" rel="noopener">
          <code>helm/jeffrey-testapp-server/templates/deployment.yaml</code></a>:
      </p>

      <DocsCodeBlock
        language="yaml"
        :code="envBlock"
      />

      <DocsCallout type="info">
        <strong><code>JEFFREY_TESTAPP_MODE</code></strong> is testapp-specific —
        not part of the CLI contract. It's referenced from <code>jeffrey-base.conf</code>
        via HOCON variable substitution to produce two distinct project names from one
        chart.
      </DocsCallout>

      <h2 id="base-conf">Anatomy of jeffrey-base.conf</h2>
      <p>From
        <a href="https://github.com/petrbouda/jeffrey-testapp/blob/main/helm/jeffrey-testapp-server/jeffrey-base.conf" target="_blank" rel="noopener">
          <code>helm/jeffrey-testapp-server/jeffrey-base.conf</code></a>
        — the entire file, annotated below:
      </p>

      <DocsCodeBlock
        language="hocon"
        :code="baseConf"
      />

      <p>The file is delivered as a ConfigMap and mounted at the path that
        <code>JEFFREY_BASE_CONFIG</code> points to:</p>

      <DocsCodeBlock
        language="yaml"
        :code="configMapMount"
      />

      <h2 id="project-block">Project Block</h2>
      <p>
        Controls how the workload appears in Jeffrey Server. The
        <code>name</code> is the logical identifier (used as the project key in the
        catalog DB); the <code>label</code> is the human-readable display string.
      </p>

      <DocsCodeBlock
        language="hocon"
        :code="projectBlock"
      />

      <p>
        The <code>${JEFFREY_TESTAPP_MODE}</code> reference is HOCON variable
        substitution — it resolves at <code>jeffrey-cli init</code> time against the
        environment. With <code>JEFFREY_TESTAPP_MODE=direct</code> the project becomes
        <code>direct-jeffrey-testapp-server</code>; with <code>JEFFREY_TESTAPP_MODE=dom</code>
        it becomes <code>dom-jeffrey-testapp-server</code>. One chart, two distinct
        projects in Jeffrey Server, side by side for differential analysis.
      </p>

      <h2 id="capture-blocks">Capture Blocks</h2>
      <p>Each capture feature toggles independently:</p>

      <h3>perf-counters</h3>
      <p>
        Captures JVM perfdata counters (<code>hsperfdata</code>) every cycle and bundles
        them with the recording. Useful for cross-referencing GC / safepoint / classloading
        rates without reading them out of the JFR stream.
      </p>

      <h3>heap-dump</h3>
      <p>
        <code>type = "crash"</code> writes a heap dump only when the JVM crashes (via
        <code>-XX:HeapDumpOnOutOfMemoryError</code> + crash hooks). Set
        <code>type = "always"</code> for opt-in dump-per-cycle, or <code>enabled =
        false</code> to disable entirely.
      </p>

      <h3>jvm-logging</h3>
      <p>
        Wires up <code>-Xlog:</code> with the supplied command. The
        <code>&lt;&lt;JEFFREY_CURRENT_SESSION&gt;&gt;</code> placeholder is expanded by the
        CLI to the per-cycle session directory, so each recording lands in its own folder
        with its own rolling log file.
      </p>

      <h2 id="jvm-options">Additional JVM Options</h2>
      <p>
        <code>additional-jvm-options</code> is appended verbatim to the JVM launch line —
        it's where the testapp pins heap size, GC choice, and any other JVM flags. The
        same placeholder system applies (<code>&lt;&lt;JEFFREY_CURRENT_SESSION&gt;&gt;</code>,
        <code>&lt;&lt;JEFFREY_PROFILER_PATH&gt;&gt;</code>, etc.).
      </p>

      <DocsCallout type="tip">
        Keep <code>additional-jvm-options</code> short — it composes with profiler agent
        flags injected automatically by <code>jeffrey-cli</code>. Use it for heap sizing
        and GC tuning, not for tweaking the profiler (do that on the
        <router-link to="/docs/microscope/profiler-settings">Profiler Settings</router-link>
        page in Microscope, which propagates to every monitored pod via Jeffrey Server's
        gRPC API).
      </DocsCallout>

      <h2 id="omitted-paths">Why Paths Are Omitted</h2>
      <p>
        The conf file deliberately leaves out <code>jeffrey-home</code>,
        <code>profiler-path</code>, <code>agent-path</code>, and <code>cli-path</code>.
        That's because:
      </p>

      <ul>
        <li><code>jeffrey-home</code> is read from the <code>JEFFREY_HOME</code> env var (set by the chart from <code>sharedVolume.mountPath</code>).</li>
        <li><code>profiler-path</code> defaults to <code>${jeffrey-home}/libs/current/libasyncProfiler.so</code>.</li>
        <li><code>agent-path</code> defaults to <code>${jeffrey-home}/libs/current/jeffrey-agent.jar</code>.</li>
        <li><code>cli-path</code> defaults to <code>${jeffrey-home}/libs/current/jeffrey-cli-&lt;arch&gt;</code>.</li>
      </ul>

      <p>
        Each value baked by the JIB extension at image build time matches what
        <code>copy-libs</code> writes at runtime, so the conf file stays small and the
        same template works for every monitored pod regardless of which Jeffrey Server
        version published the bundle.
      </p>
    </div>

    <DocsNavFooter />
  </article>
</template>

<style scoped>
@import '@/views/docs/docs-page.css';
</style>
