

package io.jafar.parser;

import io.jafar.parser.JFRValueDeserializer;
import io.jafar.parser.internal_api.DeserializationHandler;

import java.util.HashMap;
import java.util.Map;

public final class Deserializers {
    private final Map<String, DeserializationHandler<?>> deserializers = new HashMap<>();

    public void addDeserializer(String name, JFRValueDeserializer<?> deserializer) {
        deserializers.put(name, deserializer);
    }

    // Used from handler generated bytecode
    public <T> DeserializationHandler<?> getDeserializer(String name) {
        return deserializers.get(name);
    }

    public DeserializationHandler<?> putIfAbsent(String key, DeserializationHandler<?> value) {
        return deserializers.putIfAbsent(key, value);
    }

    public void clear() {
        deserializers.clear();
    }
}
