// Keep tree structure and files will be automatically created if missing
filesystem {
    jeffrey = ${HOME}/.jeffrey
    jfr = ${filesystem.jeffrey}/jfr
    repository = ${filesystem.jeffrey}/repository
}

scheduler {
    default_period = 30s
}