package pbouda.jeffrey.workspace;

import pbouda.jeffrey.common.Json;
import pbouda.jeffrey.common.model.workspace.WorkspaceEvent;
import pbouda.jeffrey.common.model.workspace.WorkspaceEventType;
import pbouda.jeffrey.common.model.workspace.WorkspaceInfo;
import pbouda.jeffrey.repository.model.RemoteProject;
import pbouda.jeffrey.repository.model.RemoteSession;
import pbouda.jeffrey.workspace.model.ProjectCreatedEventContent;
import pbouda.jeffrey.workspace.model.SessionCreatedEventContent;

import java.time.Instant;

public abstract class WorkspaceEventConverter {

    public static WorkspaceEvent projectCreated(
            Instant currentInstant, RemoteProject event, WorkspaceInfo workspaceInfo) {

        ProjectCreatedEventContent content = new ProjectCreatedEventContent(
                event.projectName(),
                event.projectLabel(),
                event.repositoryType(),
                event.attributes());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.projectId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant
        );
    }

    public static WorkspaceEvent sessionCreated(
            Instant currentInstant, RemoteSession event, WorkspaceInfo workspaceInfo) {

        SessionCreatedEventContent content = new SessionCreatedEventContent(
                event.relativePath(),
                event.workspacesPath(),
                event.profilerSettings());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.sessionId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.SESSION_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant
        );
    }

    public static WorkspaceEvent sessionDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            String sessionId) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectId,
                workspaceId,
                WorkspaceEventType.SESSION_DELETED,
                null,
                null,
                currentInstant
        );
    }

    public static WorkspaceEvent projectDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                projectId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_DELETED,
                null,
                null,
                currentInstant
        );
    }
}
