/*
 * Jeffrey
 * Copyright (C) 2026 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package cafe.jeffrey.shared.persistence;

public enum StatementLabel {
    WAL_CHECK_POINT,
    RECREATE_TABLE_CLUSTERED,

    /**
     * {@link GroupLabel#INTERNAL_PROFILES}
     */
    INSERT_PROFILE,

    /**
     * {@link GroupLabel#PROJECT_RECORDINGS}
     */
    INSERT_GROUP,
    INSERT_RECORDING,
    INSERT_RECORDING_FILE,
    GROUP_EXISTS,
    FIND_RECORDING,
    FIND_ALL_RECORDINGS,
    FIND_RECORDING_FILES,
    FIND_RECORDINGS_IN_GROUP,
    FIND_ALL_RECORDING_FILES,
    FIND_GROUP,
    FIND_ALL_GROUPS,
    DELETE_RECORDING,
    DELETE_RECORDING_FILES,
    DELETE_GROUP,
    UPDATE_RECORDING_GROUP,
    INSERT_RECORDING_TAG,
    FIND_RECORDING_TAGS,
    FIND_RECORDING_TAGS_FOR_MANY,
    DELETE_RECORDING_TAGS,

    /**
     * {@link GroupLabel#PROFILE_CACHE}
     */
    INSERT_CACHE_ENTRY,
    KEY_EXISTS,
    FIND_CACHE_ENTRY,

    /**
     * {@link GroupLabel#PROFILE_EVENTS}
     */
    FIND_LATEST_JSON,
    STREAM_EVENTS,
    LOAD_FRAMES_CACHE,
    LIST_SPANS,
    SPAN_EVENTS,
    LOAD_SPAN_NAME_TEMPLATES,
    DERIVE_TRACE_SPANS,
    DERIVE_METHOD_TRACE_WEIGHTS,
    METHOD_TRACES_EXIST,
    DERIVE_BLOCKING_SPANS,
    DERIVE_TRACES,
    DERIVE_TRACE_NOTIFICATIONS,
    DERIVE_TRACE_EXCEPTIONS,
    TRACE_NOTIFICATIONS,
    TRACE_EXCEPTIONS,
    TRACE_STACKTRACE,
    TRACE_BY_ID,
    TRACE_SPANS,
    TRACE_OPERATIONS,
    COUNT_TRACE_OPERATIONS,
    TRACE_OPERATION_TRACES,
    TRACE_OPERATION_TIMELINE,
    TRACE_OPERATION_SPAN_BREAKDOWN,
    TRACE_OPERATION_THREADS,
    TRACE_OPERATION_SPANS,
    TRACE_OVERVIEW,
    TRACES_EXIST,
    SPAN_EVENT_TYPES_EXIST,
    TRACE_SPAN_EVENTS,
    TRACE_PAUSES,
    TRACE_THROTTLE_WINDOWS,
    TRACE_SPAN_CONTEXT,
    TRACE_EVENT_FIELDS,
    DERIVE_TRACE_ATTRIBUTES,
    TRACE_ATTRIBUTE_KEYS,
    TRACE_ATTRIBUTE_EVENT_TYPES,
    TRACE_ATTRIBUTE_SEARCH,
    COUNT_TRACE_ATTRIBUTE_SEARCH,
    TRACE_ATTRIBUTE_SEARCH_STATS,
    TRACE_ATTRIBUTE_SEARCH_HITS,
    TRACE_ATTRIBUTE_TIMELINE,
    TRACE_ATTRIBUTE_VALUES,
    TRACE_ATTRIBUTE_LATENCY,

    /**
     * {@link GroupLabel#ALLOCATING_THREADS}
     */
    ALLOCATING_THREADS,

    /**
     * {@link GroupLabel#PROFILE_EVENT_TYPES}
     */
    FIELDS_WITH_EVENT_TYPE,
    FIELDS_WITH_SINGLE_EVENT,
    FIELDS_WITH_EVENT_TYPES,
    DURATION_STATS_BY_TYPE,
    CPU_TIME_SAMPLE_LOSS,
    CONTAINS_EVENT,
    STRING_RELATED_FLAGS,
    ALL_FLAGS,
    COLUMNS_BY_SINGLE_EVENT,
    EVENT_SUMMARIES,
    FIND_EVENT_TYPE,

    /**
     * {@link GroupLabel#PROFILES}
     */
    FIND_PROFILE,
    ENABLED_PROFILE,
    UPDATE_PROFILE_NAME,
    MARK_PROFILE_MODIFIED,
    DELETE_PROFILE,
    INSERT_PROFILE_INFO,
    FIND_PROFILE_INFO,

    /**
     * {@link GroupLabel#PROJECTS}
     */
    FIND_ALL_PROJECTS,
    FIND_PROJECTS_BY_WORKSPACE,
    FIND_PROJECTS_BY_WORKSPACE_INCLUDING_DELETED,
    INSERT_PROJECT,
    PURGE_DELETED_PROJECTS,

    /**
     * {@link GroupLabel#SINGLE_PROJECT}
     */
    FIND_ALL_PROFILES,
    DELETE_PROJECT,
    FIND_PROJECT,
    FIND_PROJECT_INCLUDING_DELETED,
    FIND_PROJECT_BY_ORIGIN_ID,
    UPDATE_PROJECT_NAME,
    RESTORE_PROJECT,

    /**
     * {@link GroupLabel#PROJECT_REPOSITORIES}
     */
    INSERT_REPOSITORY,
    FIND_ALL_REPOSITORIES,
    DELETE_REPOSITORY,
    DELETE_ALL_REPOSITORIES,

    /**
     * {@link GroupLabel#EVENT_WRITERS}
     */
    INSERT_EVENT_TYPES,
    INSERT_EVENTS,
    INSERT_FIELD_TEXTS,
    INSERT_STACKTRACES,
    INSERT_THREADS,
    INSERT_FRAMES,

    /**
     * {@link GroupLabel#NATIVE_LEAK_EVENTS}
     */
    FIND_NATIVE_LEAK_EVENTS_SAMPLES_AND_WEIGHT,
    FIND_MALLOC_EVENT_TYPE_COLUMNS,
    MALLOC_AND_FREE_EXISTS,

    /**
     * {@link GroupLabel#WORKSPACES}
     */
    FIND_ALL_WORKSPACES,
    FIND_WORKSPACE_BY_ID,
    FIND_WORKSPACE_BY_REFERENCE_ID,
    INSERT_WORKSPACE,
    DELETE_WORKSPACE,
    CHECK_NAME_EXISTS,

    /**
     * {@link GroupLabel#REMOTE_SERVERS}
     */
    FIND_ALL_REMOTE_SERVERS,
    FIND_REMOTE_SERVER_BY_ID,
    INSERT_REMOTE_SERVER,
    DELETE_REMOTE_SERVER,
    FIND_PROJECTS_BY_WORKSPACE_ID,
    INSERT_WORKSPACE_SESSION,
    DELETE_WORKSPACE_SESSION,
    FIND_SESSIONS_BY_PROJECT_ID,
    FIND_SESSION_BY_PROJECT_AND_SESSION_ID,
    FIND_SESSION_WITH_REPOSITORY_BY_SESSION_ID,
    FIND_UNFINISHED_SESSIONS,
    FIND_UNFINISHED_SESSIONS_BY_INSTANCE_ID,
    FIND_LATEST_SESSION_ID,
    UPDATE_SESSION_FINISHED,
    UPDATE_SESSION_RETAINED,

    /**
     * {@link GroupLabel#PROFILER}
     */
    UPSERT_PROFILER_SETTINGS,
    FIND_PROFILER_SETTINGS,
    DELETE_PROFILER_SETTINGS,

    /**
     * {@link GroupLabel#PROJECT_INSTANCES}
     */
    FIND_ALL_PROJECT_INSTANCES,
    FIND_PROJECT_INSTANCE_BY_ID,
    FIND_PROJECT_INSTANCES_BY_STATUS,
    FIND_PROJECT_INSTANCE_SESSIONS,
    FIND_INSTANCE_BY_ID,
    FIND_SESSIONS_BY_INSTANCE_ID,
    FIND_PROJECT_INSTANCE_SESSIONS_BY_PROJECT_ID,
    INSERT_PROJECT_INSTANCE,
    UPDATE_PROJECT_INSTANCE_STATUS,
    UPDATE_PROJECT_INSTANCE_STATUS_AND_FINISHED_AT,
    UPDATE_PROJECT_INSTANCE_STATUS_AND_EXPIRED_AT,
    SET_PROJECT_INSTANCE_EXPIRING_AT,
    DELETE_PROJECT_INSTANCE,

    FIND_ALL_PROJECT_NAMESPACES,

    /**
     * {@link GroupLabel#PROFILE_FRAMES}
     */
    COUNT_FRAMES_BY_CLASS_NAME,
    PREVIEW_RENAME_FRAMES,
    RENAME_FRAME_CLASS_NAMES,

    /**
     * {@link GroupLabel#PROFILE_TOOLS}
     */
    TOOLS_COUNT_MATCHING_FRAMES,
    TOOLS_SAMPLE_MATCHING_FRAMES,
    TOOLS_COUNT_AFFECTED_STACKTRACES,
    TOOLS_FIND_MATCHING_FRAME_HASHES,
    TOOLS_FIND_AFFECTED_STACKTRACES,
    TOOLS_INSERT_SYNTHETIC_FRAME,
    TOOLS_UPDATE_EVENTS_STACKTRACE,
    TOOLS_DELETE_STACKTRACES,
    TOOLS_INSERT_STACKTRACE,
    TOOLS_DELETE_ORPHANED_FRAMES,
    TOOLS_DELETE_ORPHANED_STACKTRACES,
    TOOLS_DELETE_ORPHANED_THREADS,
    TOOLS_DELETE_EVENTS_BY_STACKTRACES,

    /**
     * {@link GroupLabel#PROFILE_CACHE}
     */
    DELETE_ALL_CACHE,

    /**
     * {@link GroupLabel#SETTINGS}
     */
    FIND_ALL_SETTINGS,
    FIND_SETTINGS_BY_CATEGORY,
    FIND_SETTING,
    UPSERT_SETTING,
    DELETE_SETTING,
    DELETE_SETTINGS_BY_CATEGORY,

    /**
     * {@link GroupLabel#ADVISOR}
     */
    FIND_ADVISOR_PROMPTS,
    UPSERT_ADVISOR_PROMPT,
    FIND_ADVISOR_RECOMMENDATIONS,
    UPSERT_ADVISOR_RECOMMENDATION,
    FIND_ADVISOR_SETTINGS,
    UPSERT_ADVISOR_SETTINGS,
    DELETE_ALL_ADVISOR_PROMPTS,
    DELETE_ALL_ADVISOR_RECOMMENDATIONS,
    FIND_ALL_ADVISOR_PROJECT_FOLDERS,
    FIND_ADVISOR_PROJECT_FOLDER,
    FIND_ADVISOR_PROJECT_FOLDER_BY_NAME,
    INSERT_ADVISOR_PROJECT_FOLDER,
    UPDATE_ADVISOR_PROJECT_FOLDER,
    DELETE_ADVISOR_PROJECT_FOLDER,

    /**
     * {@link GroupLabel#PIPELINE_RUNS}
     */
    FIND_PIPELINE_RUN,
    FIND_PIPELINE_RUNS,
    UPSERT_PIPELINE_RUN,
    DELETE_PIPELINE_RUNS
}
