package cafe.jeffrey.hub.core.workspace;

import cafe.jeffrey.shared.common.model.workspace.event.InstanceCreatedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.InstanceExpiredEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.InstanceFinishedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.ProjectCreatedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.SessionCreatedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.SessionFileCreatedEventContent;
import cafe.jeffrey.shared.common.Json;
import cafe.jeffrey.shared.common.model.ProjectInfo;
import cafe.jeffrey.shared.common.model.ProjectInstanceSessionInfo;
import cafe.jeffrey.shared.common.model.repository.RecordingSession;
import cafe.jeffrey.shared.common.model.repository.RemoteProject;
import cafe.jeffrey.shared.common.model.repository.RepositoryFile;
import cafe.jeffrey.shared.common.model.repository.RemoteProjectInstance;
import cafe.jeffrey.shared.common.model.repository.RemoteProjectInstanceSession;
import cafe.jeffrey.shared.common.model.workspace.CLIWorkspaceEvent;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEvent;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEventCreator;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEventType;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceInfo;

import java.time.Instant;

public abstract class WorkspaceEventConverter {

    /**
     * Converts a CLI wire-format event into the internal {@link WorkspaceEvent},
     * supplying the queue-infrastructure {@code createdAt} timestamp that the CLI
     * cannot meaningfully provide.
     */
    public static WorkspaceEvent fromCLIEvent(CLIWorkspaceEvent message, Instant createdAt) {
        return new WorkspaceEvent(
                null,
                message.originEventId(),
                message.projectId(),
                message.workspaceRefId(),
                message.eventType(),
                message.content(),
                message.originCreatedAt(),
                createdAt,
                message.createdBy());
    }

    public static WorkspaceEvent projectCreated(
            Instant currentInstant,
            RemoteProject event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        ProjectCreatedEventContent content = new ProjectCreatedEventContent(
                event.projectName(),
                event.projectLabel(),
                event.workspacesPath(),
                event.relativeWorkspacePath(),
                event.relativeProjectPath(),
                event.repositoryType(),
                event.attributes());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.projectId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent instanceCreated(
            Instant currentInstant,
            RemoteProjectInstance event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        InstanceCreatedEventContent content = new InstanceCreatedEventContent(
                event.relativeInstancePath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.instanceId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionCreated(
            Instant currentInstant,
            RemoteProjectInstanceSession event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        SessionCreatedEventContent content = new SessionCreatedEventContent(
                event.instanceId(),
                event.order(),
                event.relativeSessionPath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.sessionId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            String sessionId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionFinished(
            Instant currentInstant,
            ProjectInfo projectInfo,
            ProjectInstanceSessionInfo sessionInfo,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionInfo.sessionId(),
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_FINISHED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    /**
     * Builds a file-created event for one repository file. The file's id becomes the
     * {@code originEventId}, which makes the queue's dedup key
     * ({@code projectId:originEventId:eventType}) stable across ticks and across LZ4
     * compression — the id has recording extensions stripped, so {@code foo.jfr} and
     * {@code foo.jfr.lz4} never look like two different files.
     */
    public static WorkspaceEvent sessionFileCreated(
            Instant currentInstant,
            ProjectInfo projectInfo,
            RecordingSession session,
            RepositoryFile file,
            WorkspaceEventCreator createdBy) {

        SessionFileCreatedEventContent content = new SessionFileCreatedEventContent(
                session.instanceId(),
                session.id(),
                file.name(),
                file.fileType(),
                file.fileType().fileCategory(),
                file.size() != null ? file.size() : 0L,
                file.createdAt());

        WorkspaceEventType eventType = file.isRecordingFile()
                ? WorkspaceEventType.PROJECT_INSTANCE_SESSION_RECORDING_FILE_CREATED
                : WorkspaceEventType.PROJECT_INSTANCE_SESSION_ARTIFACT_FILE_CREATED;

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                file.id(),
                projectInfo.id(),
                projectInfo.workspaceId(),
                eventType,
                Json.toString(content),
                file.createdAt() != null ? file.createdAt() : currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent instanceFinished(
            Instant currentInstant,
            ProjectInfo projectInfo,
            String instanceId,
            Instant finishedAt,
            WorkspaceEventCreator createdBy) {

        InstanceFinishedEventContent content = new InstanceFinishedEventContent(instanceId, finishedAt);

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                instanceId,
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.PROJECT_INSTANCE_FINISHED,
                Json.toString(content),
                finishedAt != null ? finishedAt : currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent instanceExpired(
            Instant currentInstant,
            ProjectInfo projectInfo,
            String instanceId,
            Instant expiredAt,
            WorkspaceEventCreator createdBy) {

        InstanceExpiredEventContent content = new InstanceExpiredEventContent(instanceId, expiredAt);

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                instanceId,
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.PROJECT_INSTANCE_EXPIRED,
                Json.toString(content),
                expiredAt != null ? expiredAt : currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent projectDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                projectId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }
}
