FROM petrbouda/jeffrey-builder:21

RUN apt -y install git

RUN mkdir /app && mkdir /sources

RUN git clone https://github.com/petrbouda/jeffrey.git /sources/jeffrey \
    && mvn clean package -f /sources/jeffrey/pom.xml \
    && cp /sources/jeffrey/build/build-app/target/jeffrey.jar /app

RUN  git clone https://github.com/petrbouda/jeffrey-recordings.git /sources/recordings  \
    && java -jar /app/jeffrey.jar upload-recordings /sources/recordings \
    && rm -rf /sources

RUN rm -rf /sources

ENTRYPOINT ["java", "-jar", "/app/jeffrey.jar"]
