FROM petrbouda/jeffrey-builder:24

RUN apt -y install git

RUN mkdir /app
RUN mkdir /sources

RUN git clone https://github.com/petrbouda/jeffrey.git /sources/jeffrey \
    && mvn clean package -f /sources/jeffrey/pom.xml \
    && cp /sources/jeffrey/build/build-app/target/jeffrey.jar /app \
    && rm -rf /sources

ENTRYPOINT ["java", "-jar", "/app/jeffrey.jar"]
