# Builder stage
FROM petrbouda/jeffrey-builder:25 AS builder

RUN apt -y install git

RUN mkdir /sources

RUN git clone https://github.com/petrbouda/jeffrey.git /sources/jeffrey \
    && mvn clean package -f /sources/jeffrey/pom.xml

# Runtime stage
FROM eclipse-temurin:25-jdk

RUN mkdir /app

COPY --from=builder /sources/jeffrey/build/build-app/target/jeffrey.jar /app/

ENTRYPOINT ["java", "-jar", "/app/jeffrey.jar"]
