# Builder stage
FROM petrbouda/jeffrey-builder:24 AS builder

RUN apt -y install git

RUN mkdir /sources

RUN git clone https://github.com/petrbouda/jeffrey.git /sources/jeffrey \
    && mvn clean package -f /sources/jeffrey/pom.xml

RUN git clone https://github.com/petrbouda/jeffrey-recordings.git /sources/recordings

# Runtime stage
FROM eclipse-temurin:24-jdk

RUN mkdir /app

COPY --from=builder /sources/jeffrey/build/build-app/target/jeffrey.jar /app/
COPY --from=builder /sources/recordings /sources/recordings

RUN java -jar /app/jeffrey.jar upload-recordings /sources/recordings
RUN rm -rf /sources

ENTRYPOINT ["java", "-jar", "/app/jeffrey.jar"]
