FROM --platform=$TARGETPLATFORM node:22

ARG MAVEN_VERSION=3.9.7
ARG JAVA_MAJOR_VERSION=21
ARG JAVA_VERSION=21.0.2
ARG JAVA_MINOR_VERSION=13
ARG TARGETPLATFORM

RUN export ARCH=$(case ${TARGETPLATFORM:-linux/amd64} in \
    "linux/amd64")   echo "x64"  ;; \
    "linux/arm64")   echo "aarch64" ;; \
    *)               echo ""        ;; esac) \
  && echo "ARCH=$ARCH"

RUN wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && tar -xvf apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && mv apache-maven-${MAVEN_VERSION} /opt \
    && rm apache-maven-${MAVEN_VERSION}-bin.tar.gz

ENV M2_HOME=/opt/apache-maven-${MAVEN_VERSION}
ENV PATH="$M2_HOME/bin:$PATH"

RUN wget https://github.com/adoptium/temurin${JAVA_MAJOR_VERSION}-binaries/releases/download/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION}/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz -P /tmp \
    && tar -xvf /tmp/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz -C /tmp \
    && mv /tmp/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION} /opt \
    && rm /tmp/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz

ENV JAVA_HOME=/opt/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION}
ENV PATH="$JAVA_HOME/bin:$PATH"

CMD ["java"]
