FROM node:22

ARG MAVEN_VERSION=3.9.11
ARG JAVA_MAJOR_VERSION=25
ARG JAVA_VERSION=25
ARG JAVA_MINOR_VERSION=36
ARG TARGETPLATFORM


RUN echo "export ARCH=$(case ${TARGETPLATFORM:-linux/amd64} in \
    'linux/amd64')    echo 'x64'  ;; \
    'linux/arm64')    echo 'aarch64' ;; \
    *)                echo ''        ;; esac)" >> /envfile

RUN . /envfile; echo "export JAVA_DOWNLOAD_URL=https://github.com/adoptium/temurin${JAVA_MAJOR_VERSION}-binaries/releases/download/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION}/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz" >> /envfile
RUN . /envfile; echo "JAVA_DOWNLOAD_URL=$JAVA_DOWNLOAD_URL"

RUN wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && tar -xvf apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && mv apache-maven-${MAVEN_VERSION} /opt \
    && rm apache-maven-${MAVEN_VERSION}-bin.tar.gz

ENV M2_HOME=/opt/apache-maven-${MAVEN_VERSION}
ENV PATH="$M2_HOME/bin:$PATH"

RUN . /envfile; wget "${JAVA_DOWNLOAD_URL}" -P /tmp \
    && tar -xvf /tmp/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz -C /tmp \
    && mv /tmp/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION} /opt \
    && rm /tmp/OpenJDK${JAVA_MAJOR_VERSION}U-jdk_${ARCH}_linux_hotspot_${JAVA_VERSION}_${JAVA_MINOR_VERSION}.tar.gz

ENV JAVA_HOME=/opt/jdk-${JAVA_VERSION}+${JAVA_MINOR_VERSION}
ENV PATH="$JAVA_HOME/bin:$PATH"

CMD ["java"]
