/*
 * Jeffrey
 * Copyright (C) 2026 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package cafe.jeffrey.init;

import java.nio.file.Path;

/**
 * Builds the content of a JVM arguments file (@argfile format).
 * Java supports this natively via {@code java @argfile} syntax since Java 9.
 * Each JVM argument is written on its own line.
 */
public class JvmArgsFileBuilder {

    public record Context(
            Path sessionPath,
            String profilerSettings
    ) {}

    /**
     * Builds the content of the @argfile from profiler settings.
     *
     * @param context the context containing session path and profiler settings string
     * @return the content of the JVM arguments file, one argument per line
     */
    public String build(Context context) {
        if (context.profilerSettings() == null || context.profilerSettings().isBlank()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# Jeffrey JVM arguments — generated by jeffrey-cli init\n");
        sb.append("# Session: ").append(context.sessionPath()).append("\n\n");

        String[] args = context.profilerSettings().trim().split("\\s+");
        for (String arg : args) {
            if (!arg.isBlank()) {
                sb.append(arg).append("\n");
            }
        }

        return sb.toString();
    }
}
