package cafe.jeffrey.server.core.workspace;

import cafe.jeffrey.shared.common.model.workspace.event.InstanceCreatedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.ProjectCreatedEventContent;
import cafe.jeffrey.shared.common.model.workspace.event.SessionCreatedEventContent;
import cafe.jeffrey.shared.common.Json;
import cafe.jeffrey.shared.common.model.ProjectInfo;
import cafe.jeffrey.shared.common.model.ProjectInstanceSessionInfo;
import cafe.jeffrey.shared.common.model.repository.RemoteProject;
import cafe.jeffrey.shared.common.model.repository.RemoteProjectInstance;
import cafe.jeffrey.shared.common.model.repository.RemoteProjectInstanceSession;
import cafe.jeffrey.shared.common.model.workspace.CLIWorkspaceEvent;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEvent;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEventCreator;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceEventType;
import cafe.jeffrey.shared.common.model.workspace.WorkspaceInfo;

import java.time.Instant;

public abstract class WorkspaceEventConverter {

    /**
     * Converts a CLI wire-format event into the internal {@link WorkspaceEvent},
     * supplying the queue-infrastructure {@code createdAt} timestamp that the CLI
     * cannot meaningfully provide.
     */
    public static WorkspaceEvent fromCLIEvent(CLIWorkspaceEvent message, Instant createdAt) {
        return new WorkspaceEvent(
                null,
                message.originEventId(),
                message.projectId(),
                message.workspaceRefId(),
                message.eventType(),
                message.content(),
                message.originCreatedAt(),
                createdAt,
                message.createdBy());
    }

    public static WorkspaceEvent projectCreated(
            Instant currentInstant,
            RemoteProject event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        ProjectCreatedEventContent content = new ProjectCreatedEventContent(
                event.projectName(),
                event.projectLabel(),
                event.workspacesPath(),
                event.relativeWorkspacePath(),
                event.relativeProjectPath(),
                event.repositoryType(),
                event.attributes());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.projectId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent instanceCreated(
            Instant currentInstant,
            RemoteProjectInstance event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        InstanceCreatedEventContent content = new InstanceCreatedEventContent(
                event.relativeInstancePath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.instanceId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionCreated(
            Instant currentInstant,
            RemoteProjectInstanceSession event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        SessionCreatedEventContent content = new SessionCreatedEventContent(
                event.instanceId(),
                event.order(),
                event.relativeSessionPath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.sessionId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            String sessionId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionFinished(
            Instant currentInstant,
            ProjectInfo projectInfo,
            ProjectInstanceSessionInfo sessionInfo,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionInfo.sessionId(),
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_FINISHED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent projectDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                projectId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }
}
