/*
 * Jeffrey
 * Copyright (C) 2026 Petr Bouda
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cafe.jeffrey.provisioner;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Builds the content of a JVM arguments file (@argfile format).
 * Java supports this natively via {@code java @argfile} syntax since Java 9.
 * Each JVM argument is written on its own line.
 */
public class JvmArgsFileBuilder {

    private static final String HEADER_COMMENT = "# Jeffrey JVM arguments — generated by provisioner init";
    private static final String SESSION_COMMENT_PREFIX = "# Session: ";
    private static final String LINE_SEPARATOR = "\n";

    public record Context(
            Path sessionPath,
            String profilerSettings
    ) {}

    /**
     * Builds the content of the @argfile from profiler settings.
     *
     * @param context the context containing session path and profiler settings string
     * @return the content of the JVM arguments file, one argument per line
     */
    public String build(Context context) {
        if (context.profilerSettings() == null || context.profilerSettings().isBlank()) {
            return "";
        }

        List<String> lines = new ArrayList<>();
        lines.add(HEADER_COMMENT);
        lines.add(SESSION_COMMENT_PREFIX + context.sessionPath());
        lines.add("");
        for (String option : JvmOptions.split(context.profilerSettings())) {
            lines.add(JvmOptions.quoteForArgFile(option));
        }

        return String.join(LINE_SEPARATOR, lines) + LINE_SEPARATOR;
    }
}
