/*
 * Jeffrey
 * Copyright (C) 2026 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


package cafe.jeffrey.hub.core.config;

import cafe.jeffrey.hub.model.config.ScopedConfigEntry;
import cafe.jeffrey.shared.common.config.ConfigType;
import cafe.jeffrey.shared.common.config.ScopedConfigLayout;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigValueFactory;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Renders a scope's stored values into the file the provisioner reads.
 *
 * <p>Deterministic by construction: types are emitted in their declaration order and each value is
 * quoted by the configuration library rather than by hand. That matters because the file's digest
 * is what tells a session whether it is still current — the same values must always produce the
 * same bytes, or every tick would look like a change.</p>
 */
public abstract class ScopedConfigRenderer {

    private ScopedConfigRenderer() {
    }

    private static final String HEADER = """
            # Generated by Jeffrey Hub. Edits here are overwritten.
            #
            # Read by the provisioner on the next JVM start, as one layer of its configuration:
            # a file in a project's folder overrides the workspace's, which overrides the one in
            # the workspaces root, and the container's own configuration overrides all three.
            """;

    private static final String ASSIGN = " = ";
    private static final String LINE_SEPARATOR = "\n";

    /** The file's content, or empty when the scope holds nothing and should have no file at all. */
    public static String render(List<ScopedConfigEntry> entries) {
        if (entries.isEmpty()) {
            return "";
        }

        Map<ConfigType, String> byType = entries.stream()
                .collect(Collectors.toMap(ScopedConfigEntry::type, ScopedConfigEntry::value));

        StringBuilder rendered = new StringBuilder(HEADER);
        for (ConfigType type : ConfigType.values()) {
            String value = byType.get(type);
            if (value != null) {
                rendered.append(ScopedConfigLayout.hoconPath(type))
                        .append(ASSIGN)
                        .append(quoted(value))
                        .append(LINE_SEPARATOR);
            }
        }
        return rendered.toString();
    }

    /** Quoting and escaping are the library's problem, not a regular expression's. */
    private static String quoted(String value) {
        return ConfigValueFactory.fromAnyRef(value).render();
    }

    /** Reads a rendered file back into values, which is how an orphaned file is adopted. */
    public static Map<ConfigType, String> parse(Config config) {
        return Arrays.stream(ConfigType.values())
                .filter(type -> config.hasPath(ScopedConfigLayout.hoconPath(type)))
                .collect(Collectors.toMap(
                        Function.identity(),
                        type -> config.getString(ScopedConfigLayout.hoconPath(type))));
    }
}
