/*
 * Jeffrey
 * Copyright (C) 2026 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package cafe.jeffrey.hub.core.config;

import cafe.jeffrey.hub.model.config.ScopedConfigEntry;
import cafe.jeffrey.shared.common.IDGenerator;
import cafe.jeffrey.shared.common.config.ConfigType;
import cafe.jeffrey.shared.common.config.ScopedConfigLayout;
import cafe.jeffrey.shared.common.filesystem.FileSystemUtils;
import com.typesafe.config.ConfigValueFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Renders a scope's stored values and writes them where the provisioner reads them.
 *
 * <p>The file is a projection of the database and nothing else: the hub is its only writer and
 * never reads one back. A scope holding nothing has no file, so publishing an empty scope removes
 * it. Rendering is deterministic — types are emitted in their declaration order and each value is
 * quoted by the configuration library rather than by hand — which is what lets an unchanged scope
 * be recognised and left alone instead of rewritten on every tick.</p>
 *
 * <p><b>The rename is what makes a concurrent reader safe.</b> A provisioner that already opened
 * the file keeps reading the old content through to the end, because the rename only swaps the
 * directory entry and the bytes it is reading live on until it closes them. Writing into the file
 * in place would instead mutate it underneath that reader, which is how the mechanism this replaced
 * could hand a JVM a half-written file and leave it unprofiled for its whole life.</p>
 *
 * <p><b>The temporary file is unique per publish.</b> An editor's save and the synchronizer's tick
 * can publish one scope at the same moment; with a shared temporary name they would interleave
 * their bytes and rename the result into place. Readers resolve the published name directly and
 * never list the directory, so the extra name costs nothing.</p>
 *
 * <p>Durability is deliberately left to the next tick rather than an {@code fsync}: no writer on
 * this volume forces its writes, a file truncated by a host crash no longer matches what the
 * database holds and is rewritten on the next run of the synchronizer, and the provisioner treats
 * an unreadable file as a skipped layer rather than a failure.</p>
 */
public class ScopedConfigPublisher {

    private static final Logger LOG = LoggerFactory.getLogger(ScopedConfigPublisher.class);

    private static final String HEADER = """
            # Generated by Jeffrey Hub. Edits here are overwritten.
            #
            # Read by the provisioner on the next JVM start, as one layer of its configuration:
            # a file in a project's folder overrides the workspace's, which overrides the one in
            # the workspaces root, and the container's own configuration overrides all three.
            """;

    private static final String ASSIGN = " = ";
    private static final String LINE_SEPARATOR = "\n";

    /** Writes what the scope holds, or removes the file when it holds nothing. */
    public void publish(Path scopeDir, List<ScopedConfigEntry> entries) {
        Path target = ScopedConfigLayout.configFile(scopeDir);
        String content = render(entries);

        if (content.isEmpty()) {
            remove(target);
            return;
        }
        if (content.equals(currentContent(target))) {
            LOG.debug("Configuration already published, leaving the file untouched: file={}", target);
            return;
        }

        FileSystemUtils.createDirectories(target.getParent());
        writeAtomically(target, content);
        LOG.info("Configuration published: file={} types={}",
                target, entries.stream().map(ScopedConfigEntry::type).toList());
    }

    /** The file's content, or {@code null} when there is none to compare against. */
    private static String currentContent(Path target) {
        if (!Files.isRegularFile(target)) {
            return null;
        }
        try {
            return Files.readString(target, StandardCharsets.UTF_8);
        } catch (IOException e) {
            LOG.warn("Cannot read a published configuration file, rewriting it: file={} error={}",
                    target, e.getMessage());
            return null;
        }
    }

    /** The file's content for a scope, empty when it holds nothing and should have no file. */
    static String render(List<ScopedConfigEntry> entries) {
        if (entries.isEmpty()) {
            return "";
        }

        Map<ConfigType, String> byType = entries.stream()
                .collect(Collectors.toMap(ScopedConfigEntry::type, ScopedConfigEntry::value));

        StringBuilder rendered = new StringBuilder(HEADER);
        for (ConfigType type : ConfigType.values()) {
            String value = byType.get(type);
            if (value != null) {
                rendered.append(ScopedConfigLayout.hoconPath(type))
                        .append(ASSIGN)
                        .append(quoted(value))
                        .append(LINE_SEPARATOR);
            }
        }
        return rendered.toString();
    }

    /** Quoting and escaping are the library's problem, not a regular expression's. */
    private static String quoted(String value) {
        return ConfigValueFactory.fromAnyRef(value).render();
    }

    private static void writeAtomically(Path target, String content) {
        Path temporary = ScopedConfigLayout.temporaryFile(target, IDGenerator.generate());
        try {
            Files.writeString(temporary, content, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target,
                        StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException e) {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to publish configuration file: " + target, e);
        } finally {
            discard(temporary);
        }
    }

    private static void remove(Path target) {
        try {
            if (Files.deleteIfExists(target)) {
                LOG.info("Configuration removed, the scope holds nothing: file={}", target);
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to remove configuration file: " + target, e);
        }
    }

    /** Best-effort: a leftover scratch file is untidy, never harmful. */
    private static void discard(Path temporary) {
        try {
            Files.deleteIfExists(temporary);
        } catch (IOException e) {
            LOG.debug("Could not remove a temporary configuration file: file={}", temporary);
        }
    }
}
