package pbouda.jeffrey.platform.workspace;

import pbouda.jeffrey.platform.workspace.model.InstanceCreatedEventContent;
import pbouda.jeffrey.platform.workspace.model.ProjectCreatedEventContent;
import pbouda.jeffrey.platform.workspace.model.RecordingFileCreatedEventContent;
import pbouda.jeffrey.platform.workspace.model.SessionCreatedEventContent;
import pbouda.jeffrey.shared.common.Json;
import pbouda.jeffrey.shared.common.filesystem.FileSystemUtils;
import pbouda.jeffrey.shared.common.model.ProjectInfo;
import pbouda.jeffrey.shared.common.model.ProjectInstanceSessionInfo;
import pbouda.jeffrey.shared.common.model.repository.RemoteProject;
import pbouda.jeffrey.shared.common.model.repository.RemoteProjectInstance;
import pbouda.jeffrey.shared.common.model.repository.RemoteProjectInstanceSession;
import pbouda.jeffrey.shared.common.model.repository.RepositoryFile;
import pbouda.jeffrey.shared.common.model.workspace.*;

import java.nio.file.Path;
import java.time.Instant;

public abstract class WorkspaceEventConverter {

    public static WorkspaceEvent projectCreated(
            Instant currentInstant,
            RemoteProject event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        ProjectCreatedEventContent content = new ProjectCreatedEventContent(
                event.projectName(),
                event.projectLabel(),
                event.workspacesPath(),
                event.relativeWorkspacePath(),
                event.relativeProjectPath(),
                event.repositoryType(),
                event.attributes());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.projectId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent instanceCreated(
            Instant currentInstant,
            RemoteProjectInstance event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        InstanceCreatedEventContent content = new InstanceCreatedEventContent(
                event.relativeInstancePath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.instanceId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionCreated(
            Instant currentInstant,
            RemoteProjectInstanceSession event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        SessionCreatedEventContent content = new SessionCreatedEventContent(
                event.instanceId(),
                event.order(),
                event.relativeSessionPath(),
                event.finishedFile(),
                event.profilerSettings(),
                event.streamingEnabled());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.sessionId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            String sessionId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionFinished(
            Instant currentInstant,
            ProjectInfo projectInfo,
            ProjectInstanceSessionInfo sessionInfo,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionInfo.sessionId(),
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.PROJECT_INSTANCE_SESSION_FINISHED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent projectDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                projectId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent recordingFileCreated(
            Instant currentInstant,
            ProjectInfo projectInfo,
            String sessionId,
            RepositoryFile originalFile,
            Path compressedPath,
            long originalSize,
            long compressedSize,
            WorkspaceEventCreator createdBy) {

        RecordingFileCreatedEventContent content = new RecordingFileCreatedEventContent(
                compressedPath.toString(),
                compressedPath.getFileName().toString(),
                originalSize,
                compressedSize,
                originalFile.createdAt(),
                FileSystemUtils.modifiedAt(compressedPath));

        Instant originCreatedAt = FileSystemUtils.modifiedAt(originalFile.filePath());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectInfo.id(),
                projectInfo.workspaceId(),
                WorkspaceEventType.RECORDING_FILE_CREATED,
                Json.toString(content),
                originCreatedAt,
                currentInstant,
                createdBy.name()
        );
    }
}
