<!--
  - Jeffrey
  - Copyright (C) 2025 Petr Bouda
  -
  - This program is free software: you can redistribute it and/or modify
  - it under the terms of the GNU Affero General Public License as published by
  - the Free Software Foundation, either version 3 of the License, or
  - (at your option) any later version.
  -
  - This program is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  - GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License
  - along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script setup lang="ts">
import { onMounted } from 'vue';
import DocsCallout from '@/components/docs/DocsCallout.vue';
import { useDocsNavigation } from '@/composables/useDocsNavigation';
import { useDocHeadings } from '@/composables/useDocHeadings';

const { adjacentPages } = useDocsNavigation();
const { setHeadings } = useDocHeadings();

const headings = [
  { id: 'what-are-recordings', text: 'What are Recordings?', level: 2 },
  { id: 'recording-contents', text: 'Recording Contents', level: 2 },
  { id: 'jfr-sources', text: 'JFR Sources', level: 2 },
  { id: 'uploading-recordings', text: 'Uploading Recordings', level: 2 },
  { id: 'creating-profiles', text: 'Creating Profiles', level: 2 }
];

onMounted(() => {
  setHeadings(headings);
});
</script>

<template>
  <article class="docs-article">
      <nav class="docs-breadcrumb">
        <router-link to="/docs" class="breadcrumb-item">
          <i class="bi bi-book me-1"></i>Docs
        </router-link>
        <span class="breadcrumb-separator">/</span>
        <span class="breadcrumb-item">Concepts</span>
        <span class="breadcrumb-separator">/</span>
        <router-link to="/docs/concepts/projects" class="breadcrumb-item">Projects</router-link>
        <span class="breadcrumb-separator">/</span>
        <span class="breadcrumb-item active">Recordings</span>
      </nav>

      <header class="docs-header">
        <div class="header-icon">
          <i class="bi bi-record-circle"></i>
        </div>
        <div class="header-content">
          <h1 class="docs-title">Recordings</h1>
        </div>
      </header>

      <div class="docs-content">
        <p>Recordings are <strong>containers</strong> that hold JFR files and associated artifacts from your Java applications.</p>

        <h2 id="what-are-recordings">What are Recordings?</h2>
        <p>A recording is a container that groups together profiling data and related artifacts captured during application execution. The primary component is a JFR (Java Flight Recorder) file, but recordings can also include additional diagnostic files.</p>

        <p>Think of a recording as a folder that bundles everything captured during a profiling session - the JFR data for flame graphs and analysis, plus supporting files like logs and memory snapshots.</p>

        <h2 id="recording-contents">Recording Contents</h2>
        <p>A recording can contain multiple types of files:</p>

        <div class="contents-grid">
          <div class="content-card primary">
            <div class="card-header">
              <i class="bi bi-file-earmark-binary"></i>
              <h4>JFR File</h4>
            </div>
            <div class="card-body">
              <p>The core profiling data in <code>.jfr</code> format. Contains events like CPU samples, allocations, locks, and more. This is used to create profiles for analysis.</p>
            </div>
          </div>
          <div class="content-card artifact">
            <div class="card-header">
              <i class="bi bi-box"></i>
              <h4>Artifacts</h4>
            </div>
            <div class="card-body">
              <p>Additional diagnostic files captured alongside the JFR:</p>
              <ul>
                <li><strong>Heap Dumps</strong> - Memory snapshots (<code>.hprof</code>)</li>
                <li><strong>JVM Logs</strong> - GC logs, JIT compilation logs</li>
                <li><strong>Perf-Counters</strong> - Hardware performance counters</li>
              </ul>
            </div>
          </div>
        </div>

        <DocsCallout type="info">
          <strong>Artifacts in analysis:</strong> All artifacts are processed during profile initialization and can add useful information to your analysis. For example, GC logs provide additional context for memory analysis, and perf-counters can reveal hardware-level bottlenecks.
        </DocsCallout>

        <h2 id="jfr-sources">JFR Sources</h2>
        <p>The JFR file within a recording can be generated by different tools:</p>

        <table>
          <thead>
            <tr>
              <th>Source</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>JDK Flight Recorder</strong></td>
              <td>Built into the JVM. Standard JFR format with comprehensive event coverage.</td>
            </tr>
            <tr>
              <td><strong>async-profiler</strong></td>
              <td>Low-overhead sampling profiler. Outputs JFR-compatible files with CPU and allocation events.</td>
            </tr>
          </tbody>
        </table>

        <h2 id="uploading-recordings">Uploading Recordings</h2>
        <p>To upload a recording to your project:</p>
        <ol>
          <li>Navigate to your project's <strong>Recordings</strong> section</li>
          <li>Click the <strong>Upload</strong> button</li>
          <li>Select a <code>.jfr</code> file from your computer</li>
          <li>Wait for the upload to complete</li>
          <li>The recording appears in the list</li>
        </ol>

        <DocsCallout type="tip">
          <strong>Repository recordings:</strong> In Live and Remote workspaces, you can also create recordings from the Repository. These recordings include all artifacts captured during the session, not just the JFR file.
        </DocsCallout>

        <h2 id="creating-profiles">Creating Profiles</h2>
        <p>To analyze a recording, you need to create a profile from its JFR file:</p>
        <ol>
          <li>Find the recording in the list</li>
          <li>Click <strong>"Create Profile"</strong></li>
          <li>Wait for initialization (depends on JFR file size)</li>
          <li>Once complete, the profile appears in the Profiles section</li>
        </ol>

        <p>For more details about profile creation and what happens during initialization, see <router-link to="/docs/concepts/projects/profiles">Profiles</router-link>.</p>
      </div>

      <nav class="docs-nav-footer">
        <router-link
          v-if="adjacentPages.prev"
          :to="`/docs/${adjacentPages.prev.category}/${adjacentPages.prev.path}`"
          class="nav-link prev"
        >
          <i class="bi bi-arrow-left"></i>
          <div class="nav-text">
            <span class="nav-label">Previous</span>
            <span class="nav-title">{{ adjacentPages.prev.title }}</span>
          </div>
        </router-link>
        <div v-else class="nav-spacer"></div>
        <router-link
          v-if="adjacentPages.next"
          :to="`/docs/${adjacentPages.next.category}/${adjacentPages.next.path}`"
          class="nav-link next"
        >
          <div class="nav-text">
            <span class="nav-label">Next</span>
            <span class="nav-title">{{ adjacentPages.next.title }}</span>
          </div>
          <i class="bi bi-arrow-right"></i>
        </router-link>
      </nav>
  </article>
</template>

<style scoped>
@import '@/views/docs/docs-page.css';

/* Contents Grid */
.contents-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin: 1.5rem 0;
}

.content-card {
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #e2e8f0;
}

.content-card .card-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  color: #fff;
}

.content-card .card-header i {
  font-size: 1.1rem;
}

.content-card .card-header h4 {
  margin: 0;
  font-size: 0.95rem;
  font-weight: 600;
}

.content-card .card-body {
  padding: 1rem;
  background: #fff;
}

.content-card .card-body p {
  margin: 0;
  font-size: 0.9rem;
  color: #495057;
}

.content-card .card-body ul {
  margin: 0.75rem 0 0 0;
  padding-left: 1.25rem;
  font-size: 0.85rem;
}

.content-card .card-body li {
  margin-bottom: 0.25rem;
  color: #495057;
}

/* Primary card (JFR File) */
.content-card.primary .card-header {
  background: linear-gradient(135deg, #5e64ff 0%, #4338ca 100%);
}

.content-card.primary {
  border-color: rgba(94, 100, 255, 0.3);
}

/* Artifact card */
.content-card.artifact .card-header {
  background: linear-gradient(135deg, #10b981 0%, #059669 100%);
}

.content-card.artifact {
  border-color: rgba(16, 185, 129, 0.3);
}

@media (max-width: 768px) {
  .contents-grid {
    grid-template-columns: 1fr;
  }
}
</style>
