/*
 * Jeffrey
 * Copyright (C) 2025 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package pbouda.jeffrey.provider.api;

public interface ProfileInitializerProvider {

    /**
     * {@link EventWriter} is used to write events to the profile. It's the same for all initializer
     * generated by this provider.
     *
     * @param eventWriter the writer to write events to the profile
     */
    void initialize(EventWriter eventWriter);

    /**
     * Creates a new profile initializer.
     *
     * @return the new profile initializer
     */
    ProfileInitializer newProfileInitializer();
}
