package cafe.jeffrey.shared.common.model.workspace;

public enum WorkspaceEventCreator {
    PROJECT_INSTANCE_SESSION_CLEANER_JOB,
    PROJECT_STORAGE_QUOTA_CLEANER_JOB,
    WORKSPACE_EVENTS_REPLICATOR_JOB,
    SESSION_FINISHED_DETECTOR_JOB,
    REPOSITORY_STORAGE,
    STREAMING_CONSUMER,
    SESSION_FILE_DETECTOR_JOB,
    INSTANCE_LIFECYCLE,
    MANUAL,
}
