<!--
  - Jeffrey
  - Copyright (C) 2025 Petr Bouda
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  -     https://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
-->

<script setup lang="ts">
import { onMounted } from 'vue';
import DocsCodeBlock from '@/components/docs/DocsCodeBlock.vue';
import DocsCallout from '@/components/docs/DocsCallout.vue';
import DocsNavFooter from '@/components/docs/DocsNavFooter.vue';
import DocsPageHeader from '@/components/docs/DocsPageHeader.vue';
import { useDocHeadings } from '@/composables/useDocHeadings';

const { setHeadings } = useDocHeadings();

const headings = [
  { id: 'input-configuration', text: 'Input Configuration', level: 2 },
  { id: 'generated-argfile', text: 'Generated @argfile', level: 2 },
  { id: 'generated-environment', text: 'Generated Environment Variables', level: 2 },
  { id: 'variable-reference', text: 'Variable Reference', level: 2 }
];

onMounted(() => {
  setHeadings(headings);
});

const generatedArgFileOutput = `# Jeffrey JVM arguments — generated by provisioner init
# Session: /tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94

-agentpath:/opt/jeffrey/libasyncProfiler.so=start,alloc,lock,event=ctimer,jfrsync=default,loop=15m,chunksize=5m,file=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/profile-%t.jfr
-XX:+UnlockDiagnosticVMOptions
-XX:+DebugNonSafepoints
-XX:+UsePerfData
-XX:PerfDataSaveFile=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/perf-counters.hsperfdata
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpGzipLevel=1
-XX:HeapDumpPath=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/heap-dump.hprof.gz
-XX:+CrashOnOutOfMemoryError
-XX:ErrorFile=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/hs-jvm-err.log
-Xmx1200m
-Xms1200m
-XX:+UseG1GC
-XX:+AlwaysPreTouch
-Xlog:gc*=debug:file=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/gc.jvm-log:time,uptime,level,tags:filecount=3,filesize=20m`;

const inputConfig = `# Jeffrey Provisioner Init Command Configuration
# Usage: provisioner init --base-config jeffrey-init.conf

# Jeffrey home directory path
jeffrey-home = "/tmp/jeffrey"

# Profiler configuration
profiler-path = "/opt/jeffrey/libasyncProfiler.so"

heartbeat { enabled = true }

# Output files
arg-file = "/tmp/jvm.args"

# Output files
env-file = "/tmp/jeffrey.env"

# Project identification
project {
    workspace-ref-id = "uat"
    name = "jeffrey"
    instance-name = "instance-1"
}

# Features

# Debug Non-Safepoints - more precise profiling (enabled by default)
debug-non-safepoints {
    enabled = true
}

# Performance counters saved into the session directory
perf-counters {
    enabled = true
}

# Liveness reporting — only set this true once the application actually carries the
# jeffrey-heartbeat dependency; the Provisioner cannot detect it and the Hub believes it.
heartbeat {
    enabled = true
}

# Heap dump on OutOfMemoryError
heap-dump {
    enabled = true
    type = "crash"  # "exit" or "crash"
}

# JDK Java Options - also exports the JDK_JAVA_OPTIONS environment variable in the .env file
jdk-java-options {
    enabled = true
}

# Extra JVM flags appended to the generated arguments — JVM unified logging goes here too.
# Use a '.jvm-log' extension so Jeffrey recognizes the file as a JVM log artifact.
additional-jvm-options = "-Xmx1200m -Xms1200m -XX:+UseG1GC -XX:+AlwaysPreTouch -Xlog:gc*=debug:file=<<JEFFREY:CURRENT_SESSION>>/gc.jvm-log:time,uptime,level,tags:filecount=3,filesize=20m"

# Attributes (key-value map)
# Supports HOCON substitution: \${VAR} (required) or \${?VAR} (optional)
attributes {
    cluster = "blue"
}`;

const generatedEnvOutput = `# ENV file with variables to source:
# /tmp/jeffrey.env
export JEFFREY_HOME=/tmp/jeffrey
export JEFFREY_WORKSPACES=/tmp/jeffrey/workspaces
export JEFFREY_CURRENT_WORKSPACE=/tmp/jeffrey/workspaces/uat
export JEFFREY_CURRENT_PROJECT=/tmp/jeffrey/workspaces/uat/jeffrey
export JEFFREY_CURRENT_SESSION=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94
export JEFFREY_FILE_PATTERN=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/profile-%t.jfr
export JEFFREY_HEARTBEAT_DIR=/tmp/jeffrey/workspaces/uat/jeffrey/instance-1/019f885e-8e69-7d65-8ac7-32a70b92cb94/.heartbeat
export JEFFREY_HEARTBEAT_ENABLED=true
export JDK_JAVA_OPTIONS='-agentpath:/opt/jeffrey/libasyncProfiler.so=start,alloc,lock,event=ctimer,jfrsync=default,loop=15m,chunksize=5m,file=<session>/profile-%t.jfr -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints ... (only when jdk-java-options.enabled = true; the argfile carries the same flags otherwise)'`;
</script>

<template>
  <article class="docs-article">
      <DocsPageHeader
        title="Generated Output"
        icon="bi bi-file-earmark-code"
      />

      <div class="docs-content">
        <p>This page shows a complete example of the Jeffrey Provisioner <code>init</code> command: the input configuration file and the generated environment variables.</p>

        <h2 id="input-configuration">Input Configuration</h2>
        <p>The following HOCON configuration file (<code>jeffrey-init.conf</code>) enables all features and demonstrates typical settings:</p>

        <DocsCodeBlock
          language="hocon"
          :code="inputConfig"
        />

        <DocsCallout type="tip">
          <strong>Run the command:</strong> Execute <code>provisioner init --base-config jeffrey-init.conf</code> to generate the output files shown below.
        </DocsCallout>

        <h2 id="generated-argfile">Generated @argfile</h2>
        <p>When <code>arg-file</code> is configured, Jeffrey Provisioner writes a JVM arguments file with one argument per line. Use it with <code>java @/tmp/jvm.args -jar app.jar</code>:</p>

        <DocsCodeBlock
          language="text"
          :code="generatedArgFileOutput"
        />

        <h2 id="generated-environment">Generated Environment Variables</h2>
        <p>When you run <code>provisioner init</code> with the above configuration, it outputs the following environment variables:</p>

        <DocsCodeBlock
          language="bash"
          :code="generatedEnvOutput"
        />

        <DocsCallout type="info">
          <strong>Using env-file:</strong> Configure <code>env-file = "/tmp/jeffrey.env"</code> in your HOCON config, then source it: <code>. /tmp/jeffrey.env</code>
        </DocsCallout>

        <h2 id="variable-reference">Variable Reference</h2>
        <p>Each generated environment variable serves a specific purpose:</p>

        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>JEFFREY_HOME</code></td>
              <td>Base directory for all Jeffrey data (from <code>jeffrey-home</code> config)</td>
            </tr>
            <tr>
              <td><code>JEFFREY_WORKSPACES</code></td>
              <td>Directory containing all workspaces (<code>$JEFFREY_HOME/workspaces</code>)</td>
            </tr>
            <tr>
              <td><code>JEFFREY_CURRENT_WORKSPACE</code></td>
              <td>Path to the current workspace directory (from <code>project.workspace-ref-id</code> config)</td>
            </tr>
            <tr>
              <td><code>JEFFREY_CURRENT_PROJECT</code></td>
              <td>Path to the current project directory (from <code>project.name</code> config)</td>
            </tr>
            <tr>
              <td><code>JEFFREY_CURRENT_SESSION</code></td>
              <td>Path to the current session directory (<code>&lt;project&gt;/&lt;instance&gt;/&lt;session-uuid&gt;</code> — a unique UUID per provisioner invocation, under the instance directory)</td>
            </tr>
            <tr>
              <td><code>JEFFREY_FILE_PATTERN</code></td>
              <td>JFR output file pattern with <code>%t</code> timestamp placeholder</td>
            </tr>
            <tr>
              <td><code>JEFFREY_HEARTBEAT_DIR</code></td>
              <td>Where the <router-link to="/docs/agent/heartbeat-library">jeffrey-heartbeat</router-link> library writes liveness files — the session's <code>.heartbeat</code> folder</td>
            </tr>
            <tr>
              <td><code>JEFFREY_HEARTBEAT_ENABLED</code></td>
              <td>What <code>heartbeat.enabled</code> declared: whether this session expects the <router-link to="/docs/agent/heartbeat-library">jeffrey-heartbeat</router-link> library to report liveness</td>
            </tr>
            <tr>
              <td><code>JDK_JAVA_OPTIONS</code></td>
              <td>The complete JVM flags, auto-picked by the JVM without an argfile (only when <code>jdk-java-options</code> is enabled)</td>
            </tr>
          </tbody>
        </table>

        <DocsCallout type="tip">
          <strong>Each exported path has an input counterpart.</strong> Every
          <code>JEFFREY_NAME</code> above is also writable as
          <code>&lt;&lt;JEFFREY:NAME&gt;&gt;</code> inside the configuration that produced it — so
          <code>&lt;&lt;JEFFREY:CURRENT_SESSION&gt;&gt;</code> in
          <code>additional-jvm-options</code> resolves to the same path
          <code>$JEFFREY_CURRENT_SESSION</code> exports. The one exception:
          <code>&lt;&lt;JEFFREY:PROFILER_PATH&gt;&gt;</code> is a placeholder without an exported
          variable. See the
          <router-link to="/docs/provisioner/configuration#placeholders">placeholder reference</router-link>.
        </DocsCallout>

        <h3>The JVM Flags</h3>
        <p>The argfile — and <code>JDK_JAVA_OPTIONS</code> when it is enabled — carries these flags,
          depending on which features are switched on:</p>

        <table>
          <thead>
            <tr>
              <th>Flag</th>
              <th>Source Feature</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>-agentpath:...libasyncProfiler.so=...</code></td>
              <td>Core profiler, always first. Left out, with a warning in the provisioner log, when the library <code>profiler-path</code> names does not exist</td>
            </tr>
            <tr>
              <td><code>-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints</code></td>
              <td><code>debug-non-safepoints { enabled = true }</code> (enabled by default)</td>
            </tr>
            <tr>
              <td><code>-XX:+UsePerfData -XX:PerfDataSaveFile=...</code></td>
              <td><code>perf-counters { enabled = true }</code></td>
            </tr>
            <tr>
              <td><code>-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=...</code></td>
              <td><code>heap-dump { enabled = true }</code></td>
            </tr>
            <tr>
              <td><code>-XX:+CrashOnOutOfMemoryError -XX:ErrorFile=...</code></td>
              <td><code>heap-dump { type = "crash" }</code></td>
            </tr>
            <tr>
              <td><code>-Xmx1200m ... -Xlog:gc*=debug:file=...</code></td>
              <td><code>additional-jvm-options = "..."</code></td>
            </tr>
          </tbody>
        </table>
      </div>

      <DocsNavFooter />
  </article>
</template>

<style scoped>
@import '@/views/docs/docs-page.css';
</style>
