package pbouda.jeffrey.platform.workspace;

import pbouda.jeffrey.common.Json;
import pbouda.jeffrey.common.model.workspace.WorkspaceEvent;
import pbouda.jeffrey.common.model.workspace.WorkspaceEventCreator;
import pbouda.jeffrey.common.model.workspace.WorkspaceEventType;
import pbouda.jeffrey.common.model.workspace.WorkspaceInfo;
import pbouda.jeffrey.platform.repository.model.RemoteProject;
import pbouda.jeffrey.platform.repository.model.RemoteSession;
import pbouda.jeffrey.platform.workspace.model.ProjectCreatedEventContent;
import pbouda.jeffrey.platform.workspace.model.SessionCreatedEventContent;

import java.time.Instant;

public abstract class WorkspaceEventConverter {

    public static WorkspaceEvent projectCreated(
            Instant currentInstant,
            RemoteProject event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        ProjectCreatedEventContent content = new ProjectCreatedEventContent(
                event.projectName(),
                event.projectLabel(),
                event.workspacesPath(),
                event.relativeWorkspacePath(),
                event.relativeProjectPath(),
                event.repositoryType(),
                event.attributes());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.projectId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.PROJECT_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionCreated(
            Instant currentInstant,
            RemoteSession event,
            WorkspaceInfo workspaceInfo,
            WorkspaceEventCreator createdBy) {

        SessionCreatedEventContent content = new SessionCreatedEventContent(
                event.relativeSessionPath(),
                event.finishedFile(),
                event.profilerSettings());

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                event.sessionId(),
                event.projectId(),
                workspaceInfo.id(),
                WorkspaceEventType.SESSION_CREATED,
                Json.toString(content),
                Instant.ofEpochMilli(event.createdAt()),
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent sessionDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            String sessionId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                sessionId,
                projectId,
                workspaceId,
                WorkspaceEventType.SESSION_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }

    public static WorkspaceEvent projectDeleted(
            Instant currentInstant,
            String workspaceId,
            String projectId,
            WorkspaceEventCreator createdBy) {

        return new WorkspaceEvent(
                null, // ID will be generated by the repository
                projectId,
                projectId,
                workspaceId,
                WorkspaceEventType.PROJECT_DELETED,
                Json.EMPTY,
                currentInstant,
                currentInstant,
                createdBy.name()
        );
    }
}
