/*
 * Jeffrey
 * Copyright (C) 2025 Petr Bouda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package pbouda.jeffrey.shared.persistence;

public enum StatementLabel {

    WAL_CHECK_POINT,

    /**
     * {@link GroupLabel#INTERNAL_PROFILES}
     */
    INSERT_PROFILE,
    MAX_EVENT_TIMESTAMP,
    UPDATE_PROFILE_FINISHED_AT,

    /**
     * {@link GroupLabel#GLOBAL_SCHEDULERS}
     */
    INSERT_GLOBAL_JOB,
    FIND_ALL_GLOBAL_JOBS,
    ENABLE_GLOBAL_JOB,
    DELETE_GLOBAL_JOB,

    /**
     * {@link GroupLabel#PROJECT_RECORDINGS}
     */
    INSERT_FOLDER,
    INSERT_RECORDING,
    INSERT_RECORDING_FILE,
    FOLDER_EXISTS,
    FIND_RECORDING,
    FIND_ALL_RECORDINGS,
    FIND_RECORDING_FILES,
    FIND_RECORDINGS_IN_FOLDER,
    FIND_ALL_RECORDING_FILES,
    FIND_ALL_FOLDERS,
    DELETE_RECORDING,
    DELETE_FOLDER,

    /**
     * {@link GroupLabel#INTERNAL_RECORDINGS}
     */
    FIND_RECORDING_INTERNAL,

    /**
     * {@link GroupLabel#PROFILE_CACHE}
     */
    INSERT_CACHE_ENTRY,
    KEY_EXISTS,
    FIND_CACHE_ENTRY,

    /**
     * {@link GroupLabel#PROFILE_EVENTS}
     */
    FIND_LATEST_JSON,
    FIND_ALL_LATEST_EVENTS,
    STREAM_EVENTS,
    LOAD_FRAMES_CACHE,

    /**
     * {@link GroupLabel#ALLOCATING_THREADS}
     */
    ALLOCATING_THREADS,

    /**
     * {@link GroupLabel#PROFILE_EVENT_TYPES}
     */
    FIELDS_WITH_EVENT_TYPE,
    FIELDS_WITH_SINGLE_EVENT,
    CONTAINS_EVENT,
    STRING_RELATED_FLAGS,
    ALL_FLAGS,
    COLUMNS_BY_SINGLE_EVENT,
    EVENT_SUMMARIES,
    FIND_EVENT_TYPE,

    /**
     * {@link GroupLabel#PROFILE_GRAPHS}
     */
    INSERT_GRAPH,
    FIND_GRAPH_CONTENT,
    FIND_ALL_METADATA,
    DELETE_GRAPH,

    /**
     * {@link GroupLabel#PROFILES}
     */
    FIND_PROFILE,
    ENABLED_PROFILE,
    UPDATE_PROFILE_NAME,
    DELETE_PROFILE,
    INSERT_PROFILE_INFO,
    FIND_PROFILE_INFO,

    /**
     * {@link GroupLabel#PROJECTS}
     */
    FIND_ALL_PROJECTS,
    FIND_PROJECTS_BY_WORKSPACE,
    INSERT_PROJECT,

    /**
     * {@link GroupLabel#SINGLE_PROJECT}
     */
    FIND_ALL_PROFILES,
    DELETE_PROJECT,
    DELETE_PROJECT_SCHEDULERS,
    DELETE_PROJECT_SESSIONS,
    DELETE_PROJECT_INSTANCES,
    DELETE_PROJECT_REPOSITORIES,
    DELETE_PROJECT_FOLDERS,
    DELETE_PROJECT_FILES,
    DELETE_PROJECT_RECORDINGS,
    DELETE_PROJECT_PROFILER_SETTINGS,
    DELETE_PROJECT_MESSAGES,
    DELETE_PROJECT_ALERTS,
    DELETE_PROJECT_PROFILES,
    FIND_PROJECT,
    FIND_PROJECT_BY_ORIGIN_ID,
    UPDATE_PROJECT_NAME,

    /**
     * {@link GroupLabel#PROJECT_REPOSITORIES}
     */
    INSERT_REPOSITORY,
    FIND_ALL_REPOSITORIES,
    DELETE_REPOSITORY,
    DELETE_ALL_REPOSITORIES,

    /**
     * {@link GroupLabel#PROJECT_SCHEDULERS}
     */
    INSERT_SCHEDULER,
    FIND_ALL_SCHEDULERS,
    ENABLE_SCHEDULER,
    DELETE_SCHEDULER,

    /**
     * {@link GroupLabel#EVENT_WRITERS}
     */
    INSERT_EVENT_TYPES,
    INSERT_EVENTS,
    INSERT_STACKTRACES,
    INSERT_STACKTRACE_TAGS,
    INSERT_THREADS,
    INSERT_FRAMES,

    /**
     * {@link GroupLabel#NATIVE_LEAK_EVENTS}
     */
    FIND_NATIVE_LEAK_EVENTS,
    FIND_NATIVE_LEAK_EVENTS_SAMPLES_AND_WEIGHT,
    FIND_MALLOC_EVENT_TYPE_COLUMNS,
    MALLOC_AND_FREE_EXISTS,

    /**
     * {@link GroupLabel#WORKSPACES}
     */
    FIND_ALL_WORKSPACES,
    FIND_WORKSPACE_BY_ID,
    INSERT_WORKSPACE,
    DELETE_WORKSPACE,
    CHECK_NAME_EXISTS,
    FIND_PROJECT_IDS_BY_WORKSPACE_ID,
    FIND_PROJECTS_BY_WORKSPACE_ID,
    INSERT_WORKSPACE_SESSION,
    DELETE_WORKSPACE_SESSION,
    FIND_SESSIONS_BY_PROJECT_ID,
    FIND_SESSION_BY_PROJECT_AND_SESSION_ID,
    FIND_UNFINISHED_SESSIONS,
    FIND_UNFINISHED_SESSIONS_BY_INSTANCE_ID,
    FIND_LATEST_SESSION_ID,
    UPDATE_SESSION_FINISHED,
    MARK_SESSION_FINISHED_WITH_HEARTBEAT,
    UPDATE_LAST_HEARTBEAT,

    /**
     * {@link GroupLabel#EXTERNAL_WORKSPACES}
     */
    FIND_ALL_EXTERNAL_WORKSPACE_PROJECTS,
    FIND_ALL_EXTERNAL_WORKSPACE_EVENTS,
    DELETE_EXTERNAL_WORKSPACE_EVENTS_BY_IDS,

    /**
     * {@link GroupLabel#PROFILER}
     */
    UPSERT_PROFILER_SETTINGS,
    FIND_PROFILER_SETTINGS,
    FIND_GLOBAL_PROFILER_SETTINGS,
    DELETE_PROFILER_SETTINGS,

    /**
     * {@link GroupLabel#PROJECT_INSTANCES}
     */
    FIND_ALL_PROJECT_INSTANCES,
    FIND_PROJECT_INSTANCE_BY_ID,
    FIND_PROJECT_INSTANCE_SESSIONS,
    INSERT_PROJECT_INSTANCE,

    FIND_ALL_PROJECT_NAMESPACES,

    /**
     * {@link GroupLabel#PERSISTENT_QUEUE}
     */
    QUEUE_APPEND,
    QUEUE_APPEND_BATCH,
    QUEUE_POLL,
    QUEUE_ACKNOWLEDGE,
    QUEUE_FIND_ALL,
    QUEUE_REGISTER_CONSUMER,
    QUEUE_FIND_CONSUMER,
    DELETE_OLD_QUEUE_EVENTS,

    /**
     * {@link GroupLabel#MESSAGES}
     */
    INSERT_MESSAGE,
    FIND_ALL_MESSAGES,
    DELETE_MESSAGES_BY_PROJECT,
    DELETE_OLD_MESSAGES,

    /**
     * {@link GroupLabel#ALERTS}
     */
    INSERT_ALERT,
    FIND_ALL_ALERTS,
    DELETE_ALERTS_BY_PROJECT,
    DELETE_OLD_ALERTS,
}
