on:
  push:
    tags:
      - '*'

name: Jeffrey Examples Docker Image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: docker/Dockerfile-examples
        tags: petrbouda/jeffrey-examples:${{ github.ref_name }},petrbouda/jeffrey-examples:latest
